name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install bc module-assistant build-essential
    - name: prepare build
      run: sudo m-a prepare
    - name: build
      run: make
